/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 energy_drink_can_500ml_-_demon_juice.glb 
Author: Aaron.MaleOreo (https://sketchfab.com/MaleOreo.)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/energy-drink-can-500ml-demon-juice-34d9a20f01c14d9089ff77d723cb8af0
Title: Energy Drink Can 500ml - Demon Juice
*/


import { useGLTF, } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import {forwardRef, useRef} from 'react';

const ModelDrink = forwardRef((props, ref) => {

   

  const { nodes, materials } = useGLTF('/models/energy_drink_can_500ml_-_demon_juice.glb')

  return (
    <group ref={ref}  {...props} dispose={null}>
        <group position={[0, -11.5, -8.5]}>
        <mesh geometry={nodes.polySurface3_standardSurface6_0.geometry} material={materials.standardSurface6} />
        <mesh geometry={nodes.polySurface3_standardSurface5_0.geometry} material={materials.standardSurface5} />
    </group>
    </group>
  )

})

export default ModelDrink

useGLTF.preload('/models/energy_drink_can_500ml_-_demon_juice.glb')
