/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ice_cube_texture.glb 
Author: dig_exart_TY (https://sketchfab.com/dig_exart_ty)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ice-cube-texture-d558fa87c7f140aa9f7f738bb11ec16e
Title: Ice Cube Texture
*/

import { useGLTF, MeshTransmissionMaterial  } from '@react-three/drei'
import { useRef } from 'react'
import { useFrame } from '@react-three/fiber'

export default function Modelcube(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/ice_cube_texture.glb')

   useFrame(() => {
    if (group.current) {
      group.current.rotation.y += 0.01; // Adjust the rotation speed as needed
    }
  })
  
  return (
    <group {...props} dispose={null} ref={group}>
      <group scale={0.01}>
        <mesh geometry={nodes['Box001_Material_#25_0'].geometry} material={materials.Material_25} rotation={[-Math.PI / 2, 0, 0]} >
         <MeshTransmissionMaterial  
            backside
            samples={10}
            thickness={3}
            roughness={0.001}        // lower = clearer/glossier
            transmission={0.98}     // closer to 1 = more transparent
            ior={1.31}              // ice IOR is 1.31 in real life
            chromaticAberration={0.03}
            distortion={0.1}        // adds internal distortion like real ice
            distortionScale={0.2}
            temporalDistortion={0.1}
            color="#d0eeff"         // very light icy blue tint
          />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/models/ice_cube_texture.glb')
