/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ice_cube_texture.glb 
Author: dig_exart_TY (https://sketchfab.com/dig_exart_ty)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ice-cube-texture-d558fa87c7f140aa9f7f738bb11ec16e
Title: Ice Cube Texture
*/

import { useGLTF, MeshTransmissionMaterial  } from '@react-three/drei'
import { useRef, useMemo } from 'react'
import {useTheme} from '../context/3dcontext.jsx'
import { useFrame } from '@react-three/fiber'


export default function Modelcube(props) {

  const {isSection2Visible} = useTheme();
  const group = useRef()

  const { nodes } = useGLTF('/models/ice_cube_texture.glb')

  const cubeMaterials = useMemo(()=>(
         <MeshTransmissionMaterial  
     backside
    backsideThickness={0.3}
    samples={1}
    thickness={0.3}
    roughness={0.0}
    transmission={1}
    ior={1.31}
    chromaticAberration={0}
    distortion={0.1}
    distortionScale={0.05}
    temporalDistortion={0}
    color="#ffffff"
    envMapIntensity={1.5}
    attenuationDistance={10}
    attenuationColor="white"
    side={2}
/>
  ), [])



  useFrame(() => {
    if (group.current && isSection2Visible) {
      group.current.rotation.y += 0.03; // Adjust the rotation speed as needed
    }
  })
  
  return (
    <group {...props} dispose={null} ref={group}>
      <group scale={0.01}>
        <mesh geometry={nodes['Box001_Material_#25_0'].geometry} rotation={[-Math.PI / 2, 0, 0]} >
         {cubeMaterials}
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/models/ice_cube_texture.glb')
